stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sdelcampo/example-ci
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
